#include "./gamemodes/modules/Games/header.pwn"
#include "./gamemodes/modules/Games/core.pwn"
#include "./gamemodes/modules/Games/Arena/index.pwn"
#include "./gamemodes/modules/Games/Race/index.pwn"
#include "./gamemodes/modules/Games/handle.pwn"
#include "./gamemodes/modules/Games/commands.pwn"
